# Generated by Django 5.2.3 on 2025-06-26 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='dee_at',
            new_name='due_at',
        ),
    ]
